### ISSUE TITLE
Change the appearance of keyboard in ipad

### ISSUE THREAD

**Issue by iosdroid** [matmartinez/MMNumberKeyboard#1]
Its possible to change the appearance of the key board from right side of the screen ipad

**Comment by matmartinez** [comment]
Hello there, what do you what to achieve exactly?

**Comment by iosdroid** [comment]
Hi I need to present the keyboard like the below attachment
![export](https://cloud.githubusercontent.com/assets/3095708/12262352/7ea42b64-b94d-11e5-8eac-a802b35d8cfa.png)

**Comment by matmartinez** [comment]
Got it. Just add the keyboard to your view hierarchy and, optionally, adopt the <UIKeyInput> protocol to handle keystrokes.

You can adopt this protocol in your view controller for example. You can explicitly set the -keyInput property to your view controller if you don't want to make it the first responder. 

Hope it helps!
