### ISSUE TITLE
UITextField from MMNumberKeyboardDelegate

### ISSUE THREAD

**Issue by NDN84** [matmartinez/MMNumberKeyboard#10]
Cool keyboard, thanx! How I can get instance on UITextField from MMNumberKeyboardDelegate methods?

**Comment by matmartinez** [comment]
Hey there NDN84, I would recommend you to reference your `UITextField` from a property somewhere else in your code, like a view controller. 

It's also possible to grab it from the `-keyInput` property in the keyboard, but it can return 'nil' or another object in the responder chain (if you're using the same keyboard with multiple text fields). It will return your text field if it's being edited. 

Hope that's useful.

**Comment by NDN84** [comment]
Thx, I'm using tag property for every keyboard instance -)
