### ISSUE TITLE
how to solve move focus some uitextfield

### ISSUE THREAD

**Issue by hyuni** [matmartinez/MMNumberKeyboard#15]
how to solve move focus some uitextfield

i want process something at begin focus.
ex) previous focus editing done and new focus editing start.

but do noting

how to solve this issue?!

**Comment by matmartinez** [comment]
Hi hyuni,

If I understand you correctly, you need to take a look at the `UITextFieldDelegate` protocol. Just set yourself as the delegate of your `UITextField`:

```objc
UITextField *textField = ...;
textField.delegate = self;
```
Then implement one or more of these methods:

```objc
- textFieldShouldBeginEditing:
- textFieldDidBeginEditing:
- textFieldShouldEndEditing:
- textFieldDidEndEditing:
```

You should take a look at the [documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextFieldDelegate_Protocol/). And if you're interested in text editing changes as well, take a look at the `MMNumberKeyboardDelegate` protocol.

Hope that helps,
Matías.

**Comment by hyuni** [comment]
@matmartinez

thanks.
my code is implemented UITextField Delegate.
but MMNumberKeyboard not running sometime. keybord input is nothing.


ex)
func textFieldShouldBeginEditing(...) {
    if previousTextField != textField {
        if previousTextField.inputView as? MMNumberKeybord {
               // Do something
               previousTextField.resignFirestResponder()

textField. becomeFirestResponder()
        }
        previousTextField = textField
    }
}

**Comment by matmartinez** [comment]
I don't understand what are you trying to say there, I'm sorry. It seems this has nothing to do with `MMNumberKeyboard`, really. Please refer to Apple's documentation. I'll be closing this issue.

Matías.
