### ISSUE TITLE
TextFieldDelegates not getting called

### ISSUE THREAD

**Issue by rupammitra** [matmartinez/MMNumberKeyboard#16]
As I want to limit the text entering to a certain length, I was implementing the -(BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string method but somehow I observed it is not getting called for this textfield though the delegate is assigned.

The code for limiting the text to 10 digits is follows:

-(BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string {
     if (textField == textFieldPhone) {
        NSString *resultingString = [textField.text stringByReplacingCharactersInRange:range withString:string];
        NSInteger length = [resultingString length];
        if (length > 10)
            return NO;
        NSCharacterSet *characterSet = [[NSCharacterSet characterSetWithCharactersInString:ACCEPT_NUMERIC] invertedSet];
        NSString *filtered = [[string componentsSeparatedByCharactersInSet:characterSet] componentsJoinedByString:@""];
        return [string isEqualToString:filtered];
    }
    return YES;
}

**Comment by matmartinez** [comment]
Hi there rupammitra,

The text field won't call the `-textField:shouldChangeCharactersInRange:` method if you're using a custom `-inputView`. For this reason, you should take a look at the `MMNumberKeyboardDelegate` protocol and this method:

```- (BOOL)numberKeyboard:(MMNumberKeyboard *)numberKeyboard shouldInsertText:(NSString *)text;```

All you have to do is set the delegate of your number keyboard, like this:

```
MMNumberKeyboard *keyboard = [[MMNumberKeyboard alloc] initWithFrame:CGRectZero];
keyboard.delegate = self;
```

Hope this helps,

Matías.

**Comment by rupammitra** [comment]
Have used it. But still not worked.

**Comment by matmartinez** [comment]
What do you mean by not worked? Can you be a little more specific? 

Maybe there's a change your code is wrong. Here's a example:

```
- (BOOL)numberKeyboard:(MMNumberKeyboard *)numberKeyboard shouldInsertText:(NSString *)text
{
      const NSInteger maximumLength = 10;
     
      return (self.yourTextField.length + text.length <= maximumLength);
}
```

Friendly reminder that this is not StackOverflow. Let me know if this solves your issue.

Matías.

**Comment by rupammitra** [comment]
Yes this worked. Thanks Matias.

**Comment by matmartinez** [comment]
Great!

Matías.
