### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ZsIsMe** [matmartinez/MMNumberKeyboard#18]

**Comment by ZsIsMe** [comment]
Sory,wrong title . How to use the top-right button  to dissmiss the keyboard?

**Comment by matmartinez** [comment]
Hi ZsIsMe, do you mean the backspace key? Custom layouts are not supported on MMNumberKeyboard  but you can customize some of the keys—like the return key and the special key (which does what you intend by default).

To learn more about customization, please refer to the documentation included in `MMNumberKeyboard.h`. 

The built-in functionality already fulfils your _dismissing needs_, so I'm closing this issue. 😃

Cheers,
Matías.
