### ISSUE TITLE
Multi-line return key text

### ISSUE THREAD

**Issue by leberwurstsaft** [matmartinez/MMNumberKeyboard#21]
It would be nice if it were possible to show multi-line text on the return key.

**Comment by matmartinez** [comment]
Hi leberwurstsaft,

The return key, I believe, it's supposed to convey a simple action. Just take a look at the possible values for `UIReturnKeyType`:

```swift
enum UIReturnKeyType : Int {
    case Default
    case Go
    case Google
    case Join
    case Next
    case Route
    case Search
    case Send
    case Yahoo
    case Done
    case EmergencyCall
    case Continue
}
```

As you can see, they're all very short and simple.

I believe this feature would allow (or encourage) people to come up with more complex keyboards, and that's a non-goal for this project.

I'll be closing this issue.
Matías.

**Comment by leberwurstsaft** [comment]
I see, thanks for clarifying.
