### ISSUE TITLE
Framework doesn't work with Carthage

### ISSUE THREAD

**Issue by Vortec4800** [matmartinez/MMNumberKeyboard#25]
When running `carthage update` this error is shown:

```
*** Skipped building MMNumberKeyboard due to the error:
Dependency "MMNumberKeyboard" has no shared framework schemes
```

Looking at the Xcode project, there is a demo app target but no framework target and scheme that just builds the keyboard by itself.

**Comment by matmartinez** [comment]
I'll look into this. Thanks.

**Comment by irlabs** [comment]
It seems this issue is fixed. (Probably with the Merge pull request #19 from mdiep/carthage-support)

**Comment by matmartinez** [comment]
Closing this now.
