### ISSUE TITLE
Testing with Appium

### ISSUE THREAD

**Issue by vcooley** [matmartinez/MMNumberKeyboard#30]
I am currently e2e testing an app that uses this keyboard for several numeric fields. Currently, when I try to have the driver type text into the field I get the following error:

`Error: [element.type("4111111111111111")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}
`

Is there any fix or workaround for this issue?

**Comment by matmartinez** [comment]
No idea what to make about this. Closing it now.
