### ISSUE TITLE
 monitor textfiled output  in real time

### ISSUE THREAD

**Issue by LambentWu** [matmartinez/MMNumberKeyboard#35]
hi，How to monitor textfiled  real-time output？ I use MMNumberKeyboard in my project, but seem that do not execute this function

- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string{

   //
   NSLog(@"%@",textField.text);
    
    return YES;
}

if I cancel  MMNumberKeyboard as   inputview 0f textfiled  ?The above function will be executed！
 how do I solve it？
thank you sir

**Comment by matmartinez** [comment]
There's a demo project you can check out. There's documentation regarding the `MMNumberKeyboardDelegate` protocol you can read on the keyboard's header file.
