### ISSUE TITLE
Swift 4.0

### ISSUE THREAD

**Issue by robert-cronin** [matmartinez/MMNumberKeyboard#38]
Is there any intention to re-write this keyboard for Swift? It looks like an amazing keyboard that I'd like to integrate into my swift product

**Comment by vincentneo** [comment]
I am not the creator, obviously, but I am actually planning to rewrite this keyboard in Swift, kinda as a fork. Meanwhile, it is possible to integrate Objective C based stuff into Swift projects, did you know?

**Comment by matmartinez** [comment]
Hey there.

As @vincentneo pointed out, this little keyboard is **intended to be used with Swift**. Everything should work out of the box if you're using CocoaPods or Carthage with any version of Swift.

Will be closing this now.
