### ISSUE TITLE
iOS 12 crash

### ISSUE THREAD

**Issue by dklt** [matmartinez/MMNumberKeyboard#39]
Hi,

Reporting...
iOS12b3 seems crash at this macro,

@ MMNumberKeyboard.m

#define UIKitLocalizedString(key) [[NSBundle bundleWithIdentifier:@"com.apple.UIKit"] localizedStringForKey:key value:@"" table:nil]

**_Reproduce-able on device w/iOS12b3 and XCode10b3_**

**Comment by vincentneo** [comment]
I have tested with the example app, on release versions of iOS 12, and Xcode 10, but was unable to reproduce the error.

**Comment by matmartinez** [comment]
Cannot reproduce the issue. Closing this now.
