### ISSUE TITLE
(carthage): keyboard does not display delete and dismiss icons

### ISSUE THREAD

**Issue by rodrigoMAD** [matmartinez/MMNumberKeyboard#48]
Installing MMNumberKeyboard from Carthage does not display the icons on delete and dismiss keyboard buttons:

<Img src="https://user-images.githubusercontent.com/37989448/97719056-69176900-1aa5-11eb-8936-4fb79225bcb1.png" width="300"/>

**Comment by matmartinez** [comment]
Fixed on version 0.3.3. Thanks!
