### ISSUE TITLE
Thoughts on adding a `-` to the keypad?

### ISSUE THREAD

**Issue by emmceemoore** [matmartinez/MMNumberKeyboard#5]
Thanks for putting this together Matías!

What are your thoughts on adding support for a `-` on the keypad? (For my use case I would like for users to be able to enter in negative values.)

**Comment by matmartinez** [comment]
Hello there, emmceemoore! Thank you, that's very kind :)

I think you should try the "special key" functionality. It was made to handle situations like this!

```
-configureSpecialKeyWithImage:actionHandler:
-configureSpecialKeyWithImage:target:action:
```
Using any of those methods will replace the "dismiss" key (at the bottom left corner) with a custom image and action of your own. 

I think I'll implement this as an option in the future. People could use it if they want, right out of the box, much like the the decimal key and `allowsDecimalPoint`. 

Let me know what you think. Thank you!

**Comment by emmceemoore** [comment]
Thanks for the hint. It was easy enough to implement `-configureSpecialKeyWithImage:actionHandler:` but it doesn't appear as though I'm able to customize the style of the special key to be `MMNumberKeyboardButtonTypeWhite`.

**Comment by matmartinez** [comment]
That's correct, I'll look into that.

**Comment by emmceemoore** [comment]
I ended up embracing the gray style of button and turned it into a "+/-" button which toggles the presence of a leading "-" in the corresponding `UITextField` through a little bit of hackery.

It would be nice if there was something like `-configureSpecialKeyWithTitle:actionHandler:` (I ended up constructing a `UIImage` from an `NSString` with attributes that match the *current* style.)

**Comment by matmartinez** [comment]
That's a neat idea. I'll be working on this ASAP.

Because you resolved your issue, I'm closing this, for now. I'll be updating here when new features become available. 

Thanks a lot 😀

**Comment by ServicePal** [comment]
I like what @emmceemoore suggested. Did that ever make it into a release?

**Comment by matmartinez** [comment]
Hi @ServicePal, this is not available yet. I'm a little concerned about API misuse. I'd recommend you to use custom image designed with this purpose in mind, like Numbers.app does.
