### ISSUE TITLE
Done button title customization

### ISSUE THREAD

**Issue by ZevEisenberg** [matmartinez/MMNumberKeyboard#8]
I would like the Done button to read "Search" instead of "Done". The Apple standard set would be nice, although I'm sure people would also love the ability to set custom strings as well, since I know many people already want to customize that button on Apple's own keyboard.

This would also allow for safer localization than the current, potentially dubious mechanism of accessing the `com.apple.UIKit` bundle's localization table.

**Comment by brightsider** [comment]
@ZevEisenberg Hi! You can use my fork :)
#11

**Comment by matmartinez** [comment]
Hey everyone! I was away on vacation and did not have the chance to think about this :) I'll get to work on this shortly.

**Comment by matmartinez** [comment]
Update: **MMNumberKeyboard 0.1.5** is available with support for customizing the Return key.

Refer to the documentation included in `MMNumberKeyboard.h` to use the new `-returnKeyTitle` and `-returnKeyButtonStyle` properties.

Thank you everyone!

**Comment by brightsider** [comment]
@matmartinez thanks! it's that I wanted :+1:
