### ISSUE TITLE
UITextFieldDelegate

### ISSUE THREAD

**Issue by bitsens** [matmartinez/MMNumberKeyboard#9]
UITextField delegate not called

**Comment by matmartinez** [comment]
Hey bitsens, UIKit will actually call some of the `UITextFieldDelegate` methods (like when the text editing begins or ends) but for some reason, it won't call any of the text editing methods in the protocol. 

You should use `MMNumberKeyboardDelegate` to handle text editing. Just refer to the documentation included in `MMNumberKeyboard.h`. It's pretty straightforward.

Hope that's what you need.
